server:
  port: 3344
spring:
  application:
    name: spring-clould-config-centerd
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YILIN-U/springcolud-config.git #github上面配置中心的仓库名字
          search-paths:
            - springcloud-config
      label: main

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: config-center
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#rabbitmq相关配置
rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
