server:
  port: 8002

eureka:
  instance:
    hostname: localhost
    instance-id: payment8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-payment-sevice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: spring_cloud
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wx.springcloud.model
  configuration:
    map-underscore-to-camel-case: true


