server:
  port: 9527

eureka:
  instance:
    hostname: localhost
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: cloud-gateway
#    开启网关从注册中心发现服务
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: payment_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
#         uri: http://localhost:8001        #匹配提供服务的路由地址
         uri: lb://CLOUD-PAYMENT-SEVICE  #匹配后提供服务的路由地址
         predicates:
           - Path=/payment/getPaymentById/**   #断言,路径相匹配的进行路由转发
           - After=2020-11-03T09:50:46.180+08:00[Asia/Shanghai]

       - id: payment_routh2                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
#         uri: http://localhost:8001        #匹配提供服务的路由地址
         uri: lb://CLOUD-PAYMENT-SEVICE
         predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由转发
#            - After=2020-11-03T09:50:46.180+08:00[Asia/Shanghai]
#            - Cookie=username,wx
#             #请求头要有X-reqeust-id的属性并且值为整数的正则表达式

