server:
  port: 80

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: false

spring:
  application:
    name: cloud-orderOpenfeign-service

ribbon:
#  建立链接后读取资源所用的额时间
  ReadTimeout: 5000
#  建立链接所用的时间
  ConnectTimeout: 5000
logging:
  level:
#    以什么级别监控那个接口
    com.wx.springcloud.openfeign.PaymentFeign: debug
