server:
  port: 80
spring:
  application:
    name: cloud-orederHy-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#openfeign支持hystrix
feign:
  hystrix:
    enabled: true


